dubbo:
  application:
    name: seckill-service
  registry:
    protocol: zookeeper
    address: 106.54.13.67:2181
  protocol:
    port: 28801
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://10.249.85.247:3306/seckillsystem?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: tiger
  redis:
    port: 6379
    host: 106.53.203.18
    jedis:
      pool:
        max-active: 20
    password: 123456
  rabbitmq:
    host: 106.54.13.67
    username: java
    password: 123
    virtual-host: /java
snowflask:
  workerId: 10
  datacenterId: 1
