dubbo:
  application:
    name: user-service
  registry:
    protocol: zookeeper
    address: 106.54.13.67:2181
  protocol:
    port: 28800
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckillsystem?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: tiger
  redis:
    port: 6379
    host: 106.54.13.67
    jedis:
      pool:
        max-active: 20
    password: tiger